
name: "bluebell"
mode: "dev"
host: "localhost"
port: 8081
version: "0.1.0"

log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "localhost"
  port: 3306
  username: "root"
  password: "041135sz"
  database: "test"
  max_open_conns: 100
  max_idle_conns: 10

redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  database: 0
  pool_size: 100

snowflake:
  start_time: "2025-01-23"
  machine_id: 1
